name: Performance Benchmark

on: [push, pull_request]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pytest pytest-benchmark django

      - name: Run benchmark test
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest -v --benchmark-only
